---
abstract: 'filesystem interaction tools'
author:
  - 'Dominik Schulz <tex@cpan.org>'
build_requires:
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sys-FS
requires:
  Carp: 0
  File::Copy: 0
  File::Spec: 0
  Log::Tree::RequiredLogger: 0
  Moose: 0
  Sys::Run: 0
  feature: 0
  mro: 0
  namespace::autoclean: 0
  perl: 5.010_000
resources:
  bugtracker: https://github.com/gittex/Sys-FS/issues
  repository: git://github.com/gittex/Sys-FS.git
version: 0.11
x_authority: cpan:TEX
